version: '3'
services:
  web:
    build: .
    command: node_modules/.bin/nodemon index.js
    environment:
      - NODE_ENV=develop
      - DEBUG=app
    ports:
      - '1337:1337'
    volumes:
      - .:/home/app/web
      - /home/app/web/node_modules
  db:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: 'mongod --smallfiles --storageEngine wiredTiger --logpath=/dev/null'