const express = require('express')
const app = express()
console.log(process.env)
app.get('/', (req, res) => res.send('HELLO'))
app.listen(3000, () => console.log(process.env.NODE_ENV + ' is listen on 3000'))